### ISSUE TITLE
What does the relationship attribute expect in the route?

### ISSUE THREAD

**Issue by dant00ine** [avem-ifmsa/avem-rest-api#1]
I am getting a 422 error which I have isolated to the relationship attribute.

Ember Data sends the record to the server and I am logging the req.body before saving it with jsonapify.create() -- here's what I see:

```
{ data:
   { attributes:
      { 'business-name': 'sdah',
        owner: 'dsakl',
        slogan: null,
        address: null,
        'address-ext': null,

        ...

        'social-li': null },
     relationships: { user: [Object] },
     type: 'bizinfo' } }
```

logging req.body.data.relationships reveals:

`{ user: { data: { type: 'users', id: '56f96c2a5f1b4bd97bb9cf5a' } } }`

Any glaring mistakes here? I am attempting to build this API project to test it out myself, but the gulpfile crashes on 

```
Requiring external module babel-register
(function (exports, require, module, __filename, __dirname) { import gulp from 'gulp';
                                                                                                  ^^^^^^
```

Thanks for any help you can offer!

**Comment by alex94cp** [comment]
Hi @dant00ine, it depends on the accessor used (typically Ref or Refs). Would you mind attaching your resource definition and/or the query response?

**Comment by dant00ine** [comment]
I think the problem is that when I create a new user, I am not properly setting some sort of nullable: true attribute in the User route/schema

```
const userResource = new Resource(User, {
    "type": 'users',
    "id": {
        "value": new Property('_id'),
        "writable": false
    },
    "links": {
        "self": {
            "value": new Template('/users/${_id}'),
            "writable": false
        }
    },
    "attributes": {
        "email": new Property('email'),
        "password": {
            "value": new Property('password'),
            "readable": false
        },
        "first-name": new Property('firstName'),
        "last-name": new Property('lastName')
        // 'registration-date': new Property('registrationDate')
    },
    "relationships": {
        "bizinfo": new Ref("Bizinfo", "bizinfo"),
        "nullable": true
    }
});
```

So it looks like a glaring user error ;^^ I will spend some more time studying the JSON-api spec. I appreciate your quick response.

**Comment by dant00ine** [comment]
Generally speaking, do you have any example requests for the API? In particular I am stuck trying to create a document with an empty one-to-one relationship.
